[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NEXT_NETLIFY_RUNNER = "1"
  NPM_FLAGS = "--legacy-peer-deps"

# Next.js 플러그인 설정
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Next.js 서버사이드 렌더링을 위한 함수 설정
[functions]
  included_files = [".next/standalone/**"]
  node_bundler = "esbuild"

# Next.js 동적 라우팅 지원
[[redirects]]
  from = "/room/:roomId"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200
